version: 0.2            
phases:
  install:
    runtime-versions:
      nodejs: 12.x
    commands:
      - apt-get update -y
      - apt-get upgrade -y
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - mv instancia.yml dist/angular
      - mv appspec.yml dist/angular
      - mkdir dist/angular/scripts
      - mv scripts/* dist/angular/scripts
      - echo 'DONE'
artifacts:
  files:
    - '**/*'
  base-directory: dist/angular